name: Build

on:
  push

jobs:
  build:
    name: build-and-test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build-script: ./build-and-test.sh
          - os: windows-latest
            build-script: ./build-and-test.ps1

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Build
      run: ${{ matrix.build-script }} build

    - name: Test
      run: ${{ matrix.build-script }} test
